/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pbang.desktop_input_nilai_psb;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author rizky
 */
public class InputNilaiFrame extends javax.swing.JFrame {
    final private Color activeColor = new Color(0, 63, 143);
    final private Color inactiveColor = new Color(255, 255, 255);

    /**
     * Creates new form InputNilaiFrame
     */
    public InputNilaiFrame() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        FTFNik = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        FTFNamaLengkap = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        FTFTanggalLahir = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        BTNTarikDataNilai = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BTNPerempuan = new javax.swing.JButton();
        FTFEmail = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        FTFNomorTelepon = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        FTFAlamat = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        FTFAsalSekolah = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        FTFNamaWali = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        FTFNomorTeleponWali = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        FTFEmailWali = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BTNMajorDKV = new javax.swing.JButton();
        BTNMajorRPL = new javax.swing.JButton();
        BTNMajorBC = new javax.swing.JButton();
        BTNMajorTKJ = new javax.swing.JButton();
        BTNMajorANM = new javax.swing.JButton();
        BTNMajorGMDV = new javax.swing.JButton();
        BTNLakiLaki = new javax.swing.JButton();
        FTFNilaiMTK = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        FTFNilaiBIndo = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        FTFNilaiEnglish = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        FTFNilaiIPA = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        FTFNilaiIPS = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        FTFNilaiPPKN = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        FTFNilaiSBK = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        FTFNilaiPJOK = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        BTNLogout = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        BTNInsertDataNilai = new javax.swing.JButton();
        BTNTarikData = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(822, 640));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setMinimumSize(new java.awt.Dimension(822, 1219));

        FTFNik.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNik.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFNik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FTFNikKeyTyped(evt);
            }
        });

        jLabel1.setLabelFor(FTFNik);
        jLabel1.setText("<html>\n<p>NIK (Nomor Induk Kependudukan)<span style=\"color: #003F8F;\">*</span></p>\n</html>");

        FTFNamaLengkap.setEditable(false);
        FTFNamaLengkap.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNamaLengkap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFNamaLengkap.setText("nama lengkap");
        FTFNamaLengkap.setEnabled(false);
        FTFNamaLengkap.setFocusable(false);
        FTFNamaLengkap.setOpaque(true);

        jLabel2.setLabelFor(FTFNik);
        jLabel2.setText("<html> <p>Jenis Kelamin<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel2.setEnabled(false);

        FTFTanggalLahir.setEditable(false);
        FTFTanggalLahir.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFTanggalLahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFTanggalLahir.setText("dd/mm/yyyy");
        FTFTanggalLahir.setEnabled(false);
        FTFTanggalLahir.setFocusable(false);
        FTFTanggalLahir.setOpaque(true);

        jLabel3.setLabelFor(FTFNik);
        jLabel3.setText("<html>\n<p>Tanggal Lahir<span style=\"color: #003F8F;\">*</span></p>\n</html>");
        jLabel3.setEnabled(false);

        BTNTarikDataNilai.setBackground(new java.awt.Color(0, 63, 143));
        BTNTarikDataNilai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNTarikDataNilai.setForeground(new java.awt.Color(255, 255, 255));
        BTNTarikDataNilai.setText("Tarik Data Nilai");
        BTNTarikDataNilai.setBorder(FTFNik.getBorder());
        BTNTarikDataNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTarikDataNilaiActionPerformed(evt);
            }
        });

        jLabel4.setLabelFor(FTFNik);
        jLabel4.setText("<html>\n<p>Nama Lengkap<span style=\"color: #003F8F;\">*</span></p>\n</html>");
        jLabel4.setEnabled(false);

        BTNPerempuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNPerempuan.setForeground(new java.awt.Color(0, 63, 143));
        BTNPerempuan.setText("Perempuan");
        BTNPerempuan.setBorder(FTFNik.getBorder());
        BTNPerempuan.setFocusable(false);

        FTFEmail.setEditable(false);
        FTFEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFEmail.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFEmail.setText("example123@gmail.com");
        FTFEmail.setEnabled(false);
        FTFEmail.setFocusable(false);
        FTFEmail.setOpaque(true);

        jLabel5.setLabelFor(FTFNik);
        jLabel5.setText("<html> <p>Email<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel5.setEnabled(false);

        FTFNomorTelepon.setEditable(false);
        FTFNomorTelepon.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNomorTelepon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFNomorTelepon.setText("0812312341234");
        FTFNomorTelepon.setEnabled(false);
        FTFNomorTelepon.setFocusable(false);
        FTFNomorTelepon.setOpaque(true);

        jLabel6.setLabelFor(FTFNik);
        jLabel6.setText("<html> <p>Nomor Telepon<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel6.setEnabled(false);

        FTFAlamat.setEditable(false);
        FTFAlamat.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFAlamat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFAlamat.setText("alamat 1234");
        FTFAlamat.setEnabled(false);
        FTFAlamat.setFocusable(false);
        FTFAlamat.setOpaque(true);

        jLabel7.setLabelFor(FTFNik);
        jLabel7.setText("<html> <p>Alamat<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel7.setEnabled(false);

        FTFAsalSekolah.setEditable(false);
        FTFAsalSekolah.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFAsalSekolah.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFAsalSekolah.setText("smp 123");
        FTFAsalSekolah.setEnabled(false);
        FTFAsalSekolah.setFocusable(false);
        FTFAsalSekolah.setOpaque(true);

        jLabel8.setLabelFor(FTFNik);
        jLabel8.setText("<html> <p>Asal Sekolah<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel8.setEnabled(false);

        FTFNamaWali.setEditable(false);
        FTFNamaWali.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNamaWali.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFNamaWali.setText("nama wali");
        FTFNamaWali.setEnabled(false);
        FTFNamaWali.setFocusable(false);
        FTFNamaWali.setOpaque(true);

        jLabel9.setLabelFor(FTFNik);
        jLabel9.setText("<html> <p>Nama Wali<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel9.setEnabled(false);

        FTFNomorTeleponWali.setEditable(false);
        FTFNomorTeleponWali.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNomorTeleponWali.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFNomorTeleponWali.setText("0812312341234");
        FTFNomorTeleponWali.setEnabled(false);
        FTFNomorTeleponWali.setFocusable(false);
        FTFNomorTeleponWali.setOpaque(true);

        jLabel10.setLabelFor(FTFNik);
        jLabel10.setText("<html> <p>Nomor Telepon Wali<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel10.setEnabled(false);

        FTFEmailWali.setEditable(false);
        FTFEmailWali.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFEmailWali.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFEmailWali.setText("example123@gmail.com");
        FTFEmailWali.setEnabled(false);
        FTFEmailWali.setFocusable(false);
        FTFEmailWali.setOpaque(true);

        jLabel11.setLabelFor(FTFNik);
        jLabel11.setText("<html> <p>Email Wali<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel11.setEnabled(false);

        jLabel12.setLabelFor(FTFNik);
        jLabel12.setText("<html> <p>Jurusan Pilihan<span style=\"color: #003F8F;\">*</span></p> </html>");
        jLabel12.setEnabled(false);

        BTNMajorDKV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNMajorDKV.setForeground(new java.awt.Color(0, 63, 143));
        BTNMajorDKV.setText("DKV");
        BTNMajorDKV.setBorder(FTFNik.getBorder());
        BTNMajorDKV.setFocusable(false);

        BTNMajorRPL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNMajorRPL.setForeground(new java.awt.Color(0, 63, 143));
        BTNMajorRPL.setText("RPL");
        BTNMajorRPL.setBorder(FTFNik.getBorder());
        BTNMajorRPL.setFocusable(false);

        BTNMajorBC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNMajorBC.setForeground(new java.awt.Color(0, 63, 143));
        BTNMajorBC.setText("BC");
        BTNMajorBC.setBorder(FTFNik.getBorder());
        BTNMajorBC.setFocusable(false);

        BTNMajorTKJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNMajorTKJ.setForeground(new java.awt.Color(0, 63, 143));
        BTNMajorTKJ.setText("TKJ");
        BTNMajorTKJ.setBorder(FTFNik.getBorder());
        BTNMajorTKJ.setFocusable(false);

        BTNMajorANM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNMajorANM.setForeground(new java.awt.Color(0, 63, 143));
        BTNMajorANM.setText("ANM");
        BTNMajorANM.setBorder(FTFNik.getBorder());
        BTNMajorANM.setFocusable(false);

        BTNMajorGMDV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNMajorGMDV.setForeground(new java.awt.Color(0, 63, 143));
        BTNMajorGMDV.setText("GMDV");
        BTNMajorGMDV.setBorder(FTFNik.getBorder());
        BTNMajorGMDV.setFocusable(false);

        BTNLakiLaki.setBackground(new java.awt.Color(0, 63, 143));
        BTNLakiLaki.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNLakiLaki.setForeground(new java.awt.Color(255, 255, 255));
        BTNLakiLaki.setText("Laki-Laki");
        BTNLakiLaki.setBorder(FTFNik.getBorder());
        BTNLakiLaki.setFocusable(false);

        FTFNilaiMTK.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNilaiMTK.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel13.setLabelFor(FTFNik);
        jLabel13.setText("<html> <p>Nilai Matematika<span style=\"color: #003F8F;\">*</span></p> </html>");

        FTFNilaiBIndo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNilaiBIndo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel14.setLabelFor(FTFNik);
        jLabel14.setText("<html> <p>Nilai Bahasa Indonesia<span style=\"color: #003F8F;\">*</span></p> </html>");

        FTFNilaiEnglish.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNilaiEnglish.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel15.setLabelFor(FTFNik);
        jLabel15.setText("<html> <p>Nilai Bahasa Inggris<span style=\"color: #003F8F;\">*</span></p> </html>");

        FTFNilaiIPA.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNilaiIPA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel16.setLabelFor(FTFNik);
        jLabel16.setText("<html> <p>Nilai IPA<span style=\"color: #003F8F;\">*</span></p> </html>");

        FTFNilaiIPS.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNilaiIPS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel17.setLabelFor(FTFNik);
        jLabel17.setText("<html> <p>Nilai IPS<span style=\"color: #003F8F;\">*</span></p> </html>");

        FTFNilaiPPKN.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNilaiPPKN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel18.setLabelFor(FTFNik);
        jLabel18.setText("<html> <p>Nilai PPKN<span style=\"color: #003F8F;\">*</span></p> </html>");

        FTFNilaiSBK.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNilaiSBK.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel19.setLabelFor(FTFNik);
        jLabel19.setText("<html> <p>Nilai Seni Budaya<span style=\"color: #003F8F;\">*</span></p> </html>");

        FTFNilaiPJOK.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 63, 143), 2, true), javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
        FTFNilaiPJOK.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FTFNilaiPJOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTFNilaiPJOKActionPerformed(evt);
            }
        });

        jLabel20.setLabelFor(FTFNik);
        jLabel20.setText("<html> <p>Nilai PJOK<span style=\"color: #003F8F;\">*</span></p> </html>");

        BTNLogout.setBackground(new java.awt.Color(0, 63, 143));
        BTNLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNLogout.setForeground(new java.awt.Color(255, 255, 255));
        BTNLogout.setText("Logout");
        BTNLogout.setBorder(FTFNik.getBorder());
        BTNLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLogoutActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 63, 143));
        jTextField1.setBorder(null);
        jTextField1.setFocusable(false);

        BTNInsertDataNilai.setBackground(new java.awt.Color(0, 63, 143));
        BTNInsertDataNilai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNInsertDataNilai.setForeground(new java.awt.Color(255, 255, 255));
        BTNInsertDataNilai.setText("Insert Data Nilai");
        BTNInsertDataNilai.setBorder(FTFNik.getBorder());
        BTNInsertDataNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInsertDataNilaiActionPerformed(evt);
            }
        });

        BTNTarikData.setBackground(new java.awt.Color(0, 63, 143));
        BTNTarikData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNTarikData.setForeground(new java.awt.Color(255, 255, 255));
        BTNTarikData.setText("Tarik Data");
        BTNTarikData.setBorder(FTFNik.getBorder());
        BTNTarikData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTarikDataActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Form Input Nilai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNik, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(FTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(FTFNomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BTNLakiLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BTNPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(FTFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(FTFAsalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNamaWali, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(BTNMajorDKV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BTNMajorRPL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(BTNMajorTKJ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BTNMajorBC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNomorTeleponWali, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(BTNMajorANM, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BTNMajorGMDV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFEmailWali, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(BTNTarikData, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNilaiMTK, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(FTFNilaiPPKN, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNilaiBIndo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(FTFNilaiSBK, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNilaiEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(FTFNilaiPJOK, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNilaiIPA, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(BTNTarikDataNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(FTFNilaiIPS, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(BTNInsertDataNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTFNomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNLakiLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTFAsalSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNamaWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMajorDKV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMajorRPL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BTNMajorTKJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMajorBC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNomorTeleponWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMajorANM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMajorGMDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFEmailWali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNTarikData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNilaiMTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTFNilaiPPKN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNilaiBIndo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTFNilaiSBK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNilaiEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTFNilaiPJOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNilaiIPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BTNTarikDataNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FTFNilaiIPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(BTNInsertDataNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FTFNilaiPJOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTFNilaiPJOKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTFNilaiPJOKActionPerformed

    private void BTNLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLogoutActionPerformed
        HttpUtils.cookieManager.getCookieStore().removeAll();
        this.setVisible(false);
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_BTNLogoutActionPerformed

    private void BTNTarikDataNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTarikDataNilaiActionPerformed
        String nik = FTFNik.getText();
        HashMap<String, JTextField> gradeTextFields = new HashMap<>();
        HashMap<String, Integer> gradeValues = new HashMap<>();
        
        gradeTextFields.put("MTK", FTFNilaiMTK);
        gradeTextFields.put("BIndo", FTFNilaiBIndo);
        gradeTextFields.put("English", FTFNilaiEnglish);
        gradeTextFields.put("IPA", FTFNilaiIPA);
        gradeTextFields.put("IPS", FTFNilaiIPS);
        gradeTextFields.put("PPKN", FTFNilaiPPKN);
        gradeTextFields.put("SBK", FTFNilaiSBK);
        gradeTextFields.put("PJOK", FTFNilaiPJOK);
        
        gradeValues.put("MTK", 0);
        gradeValues.put("BIndo", 0);
        gradeValues.put("English", 0);
        gradeValues.put("IPA", 0);
        gradeValues.put("IPS", 0);
        gradeValues.put("PPKN", 0);
        gradeValues.put("SBK", 0);
        gradeValues.put("PJOK", 0);
        
        BTNTarikDataNilai.setText("Loading....");
        BTNTarikDataNilai.setForeground(activeColor);
        BTNTarikDataNilai.setEnabled(false);
        
        HttpUtils.getCandidateGrades(nik).thenAccept(response -> {
            final JSONArray data = new JSONArray(response.body());
            System.out.println(data.toString(4));
            
            data.forEach(gradeObj -> {
                final JSONObject gradeData = (JSONObject) gradeObj;
                gradeValues.put(gradeData.getString("name"), gradeData.optInt("value", 0));
            });
            
            gradeTextFields.keySet().forEach(gradeName -> {
                final JTextField gradeTextField = gradeTextFields.get(gradeName);
                final Integer gradeValue = gradeValues.get(gradeName);
                gradeTextField.setText(gradeValue.toString());
            });
            
        }).exceptionally(ex -> {
            ex.printStackTrace();
            return null;
            
        }).whenComplete((result, ex) -> {
            BTNTarikDataNilai.setText("Tarik Data Nilai");
            BTNTarikDataNilai.setForeground(inactiveColor);
            BTNTarikDataNilai.setEnabled(true);
            
        });
    }//GEN-LAST:event_BTNTarikDataNilaiActionPerformed

    private void FTFNikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FTFNikKeyTyped
        char key = evt.getKeyChar();
        
        if ( !(Character.isDigit(key) && FTFNik.getText().length() < 16) ) {
            evt.consume();
        }
    }//GEN-LAST:event_FTFNikKeyTyped

    private void BTNInsertDataNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInsertDataNilaiActionPerformed
        BTNInsertDataNilai.setText("Loading....");
        BTNInsertDataNilai.setForeground(activeColor);
        BTNInsertDataNilai.setEnabled(false);
        
        final String nik = FTFNik.getText();
        int MTK = 0,
                BIndo = 0,
                English = 0,
                IPA = 0,
                IPS = 0,
                PPKN = 0,
                SBK = 0,
                PJOK = 0;
        
        try {
            MTK = Integer.parseUnsignedInt(FTFNilaiMTK.getText());
            BIndo = Integer.parseUnsignedInt(FTFNilaiBIndo.getText());
            English = Integer.parseUnsignedInt(FTFNilaiEnglish.getText());
            IPA = Integer.parseUnsignedInt(FTFNilaiIPA.getText());
            IPS = Integer.parseUnsignedInt(FTFNilaiIPS.getText());
            PPKN = Integer.parseUnsignedInt(FTFNilaiPPKN.getText());
            SBK = Integer.parseUnsignedInt(FTFNilaiSBK.getText());
            PJOK = Integer.parseUnsignedInt(FTFNilaiPJOK.getText());
            
            if (MTK > 100 || BIndo > 100 || English > 100 || IPA > 100 || IPS > 100 || PPKN > 100 || SBK > 100 || PJOK > 100) {
                throw new Exception();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Mohon masukkan data yang valid !",
                    "Invalid Data",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        final JSONArray grades = new JSONArray();
        final HashMap<String, JTextField> gradeTextFields = new HashMap<>();
        final HashMap<String, Integer> gradeValues = new HashMap<>();
        
        gradeTextFields.put("MTK", FTFNilaiMTK);
        gradeTextFields.put("BIndo", FTFNilaiBIndo);
        gradeTextFields.put("English", FTFNilaiEnglish);
        gradeTextFields.put("IPA", FTFNilaiIPA);
        gradeTextFields.put("IPS", FTFNilaiIPS);
        gradeTextFields.put("PPKN", FTFNilaiPPKN);
        gradeTextFields.put("SBK", FTFNilaiSBK);
        gradeTextFields.put("PJOK", FTFNilaiPJOK);
        
        gradeValues.put("MTK", MTK);
        gradeValues.put("BIndo",BIndo);
        gradeValues.put("English", English);
        gradeValues.put("IPA", IPA);
        gradeValues.put("IPS", IPS);
        gradeValues.put("PPKN", PPKN);
        gradeValues.put("SBK", SBK);
        gradeValues.put("PJOK", PJOK);
        
        for (String gradeName : gradeTextFields.keySet()) {
            final int gradeValue = gradeValues.get(gradeName);
            final JSONObject gradeData = new JSONObject();
            
            gradeData.put("name", gradeName);
            gradeData.put("value", gradeValue);
            
            grades.put(gradeData);
        }
        
        System.out.println(grades.toString(4));
        
        HttpUtils.updateOrStoreCandidateGrades(nik, grades).thenAccept(response -> {
            final JSONObject result = new JSONObject(response.body());
            System.out.println(result.toString(4));
            
            final String successMessage = result.optString("success", "");
            final String errorMessage = result.optString("error", "");
            
            JOptionPane.showMessageDialog(
                    this,
                    successMessage.isBlank() ? errorMessage : successMessage,
                    successMessage.isBlank() ? "Error" : "Success",
                    successMessage.isBlank() ? JOptionPane.ERROR_MESSAGE : JOptionPane.PLAIN_MESSAGE
            );
            
        }).exceptionally(ex -> {
            ex.printStackTrace();
            return null;
            
        }).whenComplete((result, ex) -> {
            BTNInsertDataNilai.setText("Insert Data Nilai");
            BTNInsertDataNilai.setForeground(inactiveColor);
            BTNInsertDataNilai.setEnabled(true);
            
        });
    }//GEN-LAST:event_BTNInsertDataNilaiActionPerformed

    private void BTNTarikDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTarikDataActionPerformed
        String nik = FTFNik.getText();
        
        BTNLogout.setText("Loading....");
        BTNLogout.setForeground(activeColor);
        BTNLogout.setEnabled(false);
        
        HttpUtils.getSingleCandidate(nik).thenAccept(response -> {
            final JSONObject data = new JSONObject(response.body());
            System.out.println(data.toString(4));
            
            FTFNamaLengkap.setEnabled(true);
            FTFTanggalLahir.setEnabled(true);
            FTFEmail.setEnabled(true);
            FTFNomorTelepon.setEnabled(true);
            FTFAlamat.setEnabled(true);
            FTFAsalSekolah.setEnabled(true);
            FTFNamaWali.setEnabled(true);
            FTFNomorTeleponWali.setEnabled(true);
            FTFEmailWali.setEnabled(true);
            
            FTFNamaLengkap.setText(data.getString("fullname"));
            toggleGenderButton(data.getString("gender"));
            FTFTanggalLahir.setText(data.getString("birth_date"));
            FTFEmail.setText(data.getString("email"));
            FTFNomorTelepon.setText(data.getString("no_telp"));
            FTFAlamat.setText(data.getString("address"));
            FTFAsalSekolah.setText(data.getString("prev_school"));
            FTFNamaWali.setText(data.getString("parent_name"));
            FTFNomorTeleponWali.setText(data.getString("parent_telp"));
            FTFEmailWali.setText(data.getString("parent_email"));
            toggleMajorButtons(data.getString("major"));
            
        }).exceptionally(ex -> {
            ex.printStackTrace();
            return null;
            
        }).whenComplete((result, ex) -> {
            BTNLogout.setText("Tarik Data");
            BTNLogout.setForeground(inactiveColor);
            BTNLogout.setEnabled(true);
            
        });
    }//GEN-LAST:event_BTNTarikDataActionPerformed

    private void toggleGenderButton(String gender) { // is there no other way other than hardcoding the color manip? - azka
        if (gender.equals("male")) {
            toggleButton(BTNLakiLaki, true);
            toggleButton(BTNPerempuan, false);
        } else {
            toggleButton(BTNPerempuan, true);
            toggleButton(BTNLakiLaki, false);
        }
    }
    
    private void toggleMajorButtons(String majors) {
        final HashSet<String> majorsSet = new HashSet<>();
        final JButton[] majorButtons = { BTNMajorDKV, BTNMajorRPL, BTNMajorTKJ, BTNMajorBC, BTNMajorANM, BTNMajorGMDV };
        
        for (String major : majors.split(",")) {
            majorsSet.add(major);
        }
        
        for (JButton btnMajor : majorButtons) {
            toggleButton(btnMajor, majorsSet.contains(btnMajor.getText()));
        }
    }
    
    private void toggleButton(JButton button, boolean enabled) {
        button.setBackground(enabled ? activeColor : inactiveColor);
        button.setForeground(enabled ? inactiveColor : activeColor);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputNilaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputNilaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputNilaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputNilaiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputNilaiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNInsertDataNilai;
    private javax.swing.JButton BTNLakiLaki;
    private javax.swing.JButton BTNLogout;
    private javax.swing.JButton BTNMajorANM;
    private javax.swing.JButton BTNMajorBC;
    private javax.swing.JButton BTNMajorDKV;
    private javax.swing.JButton BTNMajorGMDV;
    private javax.swing.JButton BTNMajorRPL;
    private javax.swing.JButton BTNMajorTKJ;
    private javax.swing.JButton BTNPerempuan;
    private javax.swing.JButton BTNTarikData;
    private javax.swing.JButton BTNTarikDataNilai;
    private javax.swing.JFormattedTextField FTFAlamat;
    private javax.swing.JFormattedTextField FTFAsalSekolah;
    private javax.swing.JFormattedTextField FTFEmail;
    private javax.swing.JFormattedTextField FTFEmailWali;
    private javax.swing.JFormattedTextField FTFNamaLengkap;
    private javax.swing.JFormattedTextField FTFNamaWali;
    private javax.swing.JFormattedTextField FTFNik;
    private javax.swing.JFormattedTextField FTFNilaiBIndo;
    private javax.swing.JFormattedTextField FTFNilaiEnglish;
    private javax.swing.JFormattedTextField FTFNilaiIPA;
    private javax.swing.JFormattedTextField FTFNilaiIPS;
    private javax.swing.JFormattedTextField FTFNilaiMTK;
    private javax.swing.JFormattedTextField FTFNilaiPJOK;
    private javax.swing.JFormattedTextField FTFNilaiPPKN;
    private javax.swing.JFormattedTextField FTFNilaiSBK;
    private javax.swing.JFormattedTextField FTFNomorTelepon;
    private javax.swing.JFormattedTextField FTFNomorTeleponWali;
    private javax.swing.JFormattedTextField FTFTanggalLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
